version: '4.18'
services:
  nestapp:
    container_name: nestapp
    image: nest/nest-simulator:3.6
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=pg_task
      - PG_PASSWORD=root
      - PG_DB=task_db
      - PG_PORT=54320
      - PG_HOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: postgresql:lastest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '54320:54320'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}